version: '3.8'

services:

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./example-wordpress-repo/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./example-wordpress-repo/wp-content/themes/my-custom-theme:/var/www/html/wp-content/themes/my-custom-theme
      - ./backups:/var/www/html/wp-content/backups

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']

volumes:
  wordpress:
  db:
